### ISSUE TITLE
OncoKB add all entries in MTB tab doesn't add entries

### ISSUE THREAD

**Issue by Unberath** [nr23730/cbioportal-frontend#40]
The feature to add all therapy recommendations from OncoKB doesn't work for our sample patient `Testpatient`. 
Error: `Uncaught TypeError: Cannot read property 'chr' of undefined`
This probably originates from a particular OncoKB entry as it works for other samples.

**Comment by Unberath** [comment]
I've narrowed down the problem.
At TherapyRecommendationFormOncoKb.tsx:132 mutation is undefined for CNA entries, as we only search for the alteration in mutations. The code for `index`, `annotation`, and `myVariantInfo` is currently unused, do we have a use case for that @nr23730 ? If not we could switch to a similar solution for combining all alterations like in TherapyRecommendationFormAlterationInput.tsx:90

**Comment by nr23730** [comment]
Good hint! Yeah, this is supposed to look up the additional data from an alteration when it is selected (dbSNP, clinvar, cosmic, gnomad). Looks like I didn't finish that part. Will have to do this.
As CNAs don't contain lots of information in CBP they could be left out at this part.

**Comment by Unberath** [comment]
> As CNAs don't contain lots of information in CBP they could be left out at this part.

Left out as in we don't look up the additional data? So they still will be added as entries, right?

**Comment by nr23730** [comment]
> Left out as in we don't look up the additional data? So they still will be added as entries, right?

Yes.
