### ISSUE TITLE
mtbStatus

### ISSUE THREAD

**Issue by nr23730** [nr23730/cbioportal-frontend#6]
mtbStatus has inconsistencies right now:

When initially created: `DRAFT`, `COMPLETED`, `ARCHIVED`

When changed: `Draft`, `Completed`, `Archived`

Expected from JSON: `DRAFT`, `COMPLETED`, `ARCHIVED`

**Comment by Unberath** [comment]
Is this issue still relevant?

As discussed we should also rename the different states as they are confusing right now. I think it's reasonable to keep three different states for describing mtbs in preperation, ongoing mtbs and finished mtbs (although there are probably workflows that only require two states).
Do you have suggestions for the names of the new states @nr23730 ?

I think we could keep 'draft', but could also rename it to 'in preperation' or 'preliminary'.
'Completed' should be changed to something along the lines of 'in discussion' or 'in progress/process' or something simple as 'active'.
'Archived' could be renamed to 'decided' or 'completed/finished/finalised'.

While fixing the issue we should also warn users when changing a mtb to the final state.

**Comment by nr23730** [comment]
I would suggest using states vom the HL7 FHIR DiagnoaticReportStatus ValueSet: https://www.hl7.org/fhir/valueset-diagnostic-report-status.html.
This is already used in the FHIR representation but just via the following mapping:

|cBioPortal|FHIR|
|---|---|
|Draft|Preliminary|
|Completed|Final|
|Archived|Cancelled|

Either way, this issue meant something different. It is about cBioPortal transferring the String instead of the key via the REST API.

**Comment by Unberath** [comment]
Shouldn't we use Partial, Preliminary, and Final then? Or would Final already be the state where editing is disabled? If yes, what is Cancelled good for?

> Either way, this issue meant something different. It is about cBioPortal transferring the String instead of the key via the REST API.

Sorry for mixing up different issues.

**Comment by nr23730** [comment]
> Shouldn't we use Partial, Preliminary, and Final then? Or would Final already be the state where editing is disabled? If yes, what is Cancelled good for?

This is a good idea! Tbh I was a bit confused about the state `Archived` as it meant for me that it's sort of abandoned.

To make this clear (once and for all):

|cBioPortal|FHIR|Description|
|---|---|---|
|Partial|Partial|Possible therapy option prepared before MTB takes place.|
|Preliminary|Preliminary|Therapy recommendation from MTB session, lacks minor details like Pubmed reference for evidence level.|
|Final|Final|Therapy recommendation from MTB session, complete and cannot be modified.|
